### ISSUE TITLE
Bugs on hint and description copys

### ISSUE THREAD

**Issue by nicon44** [dpinones/starklings-app#100]
- functions3 hint 
``This time, the function *declaration* is okay, but there's something wrong
with the place where we're calling the function. As a reminder, you can freely play around with different solutions in Starklings! Watch mode will only jump to the next exercise if you remove the I AM NOT DONE comment.``
replace by:
``This time, the function "declaration" is okay, but there's something wrong
with the place where we're calling the function. As a reminder, you can freely play around with different solutions in Starklings!``

- enums1 hint returns null
- move_semantics2 description's lines numbers are wrong

**Comment by dpinones** [comment]
Done!
