### ISSUE TITLE
sidebar buttons look weird when sidebar is collapsed

### ISSUE THREAD

**Issue by nicon44** [dpinones/starklings-app#103]

**Comment by Ayoazeez26** [comment]
Hi @nicon44 can I pick this up?

**Comment by ktarun1419** [comment]
hi @nicon44 i want to work on this issue

**Comment by nicon44** [comment]
sorry, we're not accepting contributions for this project ATM

**Comment by WebSculptor** [comment]
Hello @nicon44, I can make it responsive
