### ISSUE TITLE
Error compiling variables1.cairo

### ISSUE THREAD

**Issue by sacha-l** [dpinones/starklings-app#105]
Not sure what the cause is but I'm not able to make the Variables 1 exercise compile (although as far as I'm aware the code is correct) see screenshot:

<img width="1501" alt="Screenshot 2024-03-13 at 17 56 17" src="https://github.com/dpinones/starklings-app/assets/23283108/5f1e533d-9f7f-4dae-b011-af00364686f4">

**Comment by ivpavici** [comment]
same for me!

**Comment by dpinones** [comment]
The Prints had been left with syntax from a previous version of Cairo. This has already been resolved.
![image](https://github.com/dpinones/starklings-app/assets/30808181/ab20ffa9-16ec-40f9-bd21-6e61edc3ccef)
