### ISSUE TITLE
Exercises in json or toml etc. files

### ISSUE THREAD

**Issue by shramee** [dpinones/starklings-app#112]
Keeping exercises in source code will make it easier to maintain and track updates.

**Comment by hardiktheprogrammer** [comment]
@shramee  I would like work on this issue , interesting for me

**Comment by shramee** [comment]
@hardiktheprogrammer I'm not maintaining this project, it was just a suggestion from my end.

**Comment by hardiktheprogrammer** [comment]
> @hardiktheprogrammer I'm not maintaining this project, it was just a suggestion from my end.

Thanks,
