### ISSUE TITLE
All exercises failing to compile

### ISSUE THREAD

**Issue by Jet-Gill-Lee** [dpinones/starklings-app#136]
Finding this issue with all exercises upon attempting to compile:

![image](https://github.com/dpinones/starklings-app/assets/87739499/b97bee7a-c15d-4633-9f22-6558e38e3c0f)

Attempting to run the same code locally is working correctly.

**Comment by nicon44** [comment]
@dpinones this fails because github user has special characters on it
POST `https://starklings-app-docker.onrender.com/api/user/Jet-Gill-Lee/exercise/intro1`

fails with
{
    "status": "error",
    "message": "Error executing scarb new"
}

**Comment by nicon44** [comment]
@Jet-Gill-Lee should be fixed now
please clear local storage and reconnect the app to github before testing again

**Comment by Jet-Gill-Lee** [comment]
@nicon44  

It's working when not logged in via GitHub - however even after clearing local storage through inspect -> application and revoking permissions through GitHub (Integrations -> applications -> Authorized OAuth Apps) and then reconnecting/authorising it returns same error. Tried on a couple of different computers

Not a big issue for me as I can just run locally but if I'm clearing the wrong local storage let me know :)

**Comment by nicon44** [comment]
@Jet-Gill-Lee 
could you please test again? it should work now
